details:
    page_title: Empty Dashboard
layout:
    - row_1_of_3:
        - col_1_of_3 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_reg1
              title: ML66 REG1
              classes:
            
            - tile_template: simple_percentage
              tile_id: precentage_chart_reg1
              title: ML66 REG1
            
        - col_1_of_3 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_reg2
              title: ML66 REG2
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_reg2
              title: ML66 REG2

        - col_1_of_3 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_aod
              title: AOD HOURLY
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_aod
              title: AOD HOURLY
  
    - row_1_of_3:
        - col_1_of_2:
            - tile_template: fancy_listing
              tile_id: health_checks
              title: "HEALTH CHECKS"
        
        - col_1_of_2:
            - tile_template: listing
              tile_id: daily_triggers
              title: "ML66 DAILY - NEXT TRIGGER"

    - row_1_of_3:
        - col_1_of_3 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_aod_daily
              title: AOD DAILY
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_aod_daily
              title: AOD DAILY

        - col_1_of_3 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_ml66_daily
              title: ML66 DAILY
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_ml66_daily
              title: ML66 DAILY
        
        - col_1_of_3 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_swat
              title: SWAT REGRESSION TRIAL
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_swat
              title: SWAT REGRESSION TRIAL