details:
    page_title: Empty Dashboard
layout:
    - row_1_of_3:
        - col_1_of_3:
            - tile_template: advanced_plot1
              tile_id: line_chart_reg1
              title: ML66 REG1
              
        - col_1_of_3:
            - tile_template: advanced_plot1
              tile_id: line_chart_reg2
              title: ML66 REG2
              classes:

        - col_1_of_3:
            - tile_template: advanced_plot1
              tile_id: aod_hourly
              title: AOD HOURLY

    - row_1_of_3:
        - col_1_of_3:
            - tile_template: fancy_listing_1
              tile_id: health_checks
              title: "HEALTH CHECKS"

        - col_2_of_3:
            - tile_template: fancy_listing_1
              tile_id: health_checks_triggers
              title: "HEALTH CHECKS"


    - row_1_of_3:
        - col_1_of_3:
            - tile_template: line_chart1
              tile_id: line_chart_aod_daily
              title: AOD DAILY
              
        - col_1_of_3:
            - tile_template: line_chart1
              tile_id: line_chart_ml66_daily
              title: ML66 DAILY
              
        - col_1_of_3:
            - tile_template: line_chart1
              tile_id: line_chart_swat
              title: SWAT REGRESSION TRIAL
              