details:
    page_title: Empty Dashboard
layout:
    - row_1_of_3:
        - col_1_of_4 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_reg1
              title: ML66 REG1
              classes:
            
            - tile_template: simple_percentage
              tile_id: precentage_chart_reg1
              title: ML66 REG1
            
        - col_1_of_4 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_reg2
              title: ML66 REG2
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_reg2
              title: ML66 REG2

        - col_1_of_4 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_aod
              title: AOD HOURLY
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_aod
              title: AOD HOURLY

        - col_1_of_4:
            - tile_template: advanced_plot
              tile_id: id_4
              title: bar_chart
              classes:
  
    - row_1_of_3:
        - col_1_of_4:
            - tile_template: just_value
              tile_id: health_check_ml66_reg1
              title: ML66 REG1

        - col_1_of_4:
            - tile_template: just_value
              tile_id: health_check_ml66_reg2
              title: ML66 REG2
              classes:

        - col_1_of_4:
            - tile_template: just_value
              tile_id: health_check_aod
              title: AOD HOURLY
              classes:

        - col_1_of_4:
            - tile_template: empty
              tile_id: empty
              title: empty Tile
              classes:


    - row_1_of_3:
        - col_1_of_3 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_aod_daily
              title: AOD DAILY
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_aod_daily
              title: AOD DAILY

        - col_1_of_3 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_ml66_daily
              title: ML66 DAILY
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_ml66_daily
              title: ML66 DAILY
        
        - col_1_of_3 flip-time-5:
            - tile_template: line_chart
              tile_id: line_chart_swat
              title: SWAT REGRESSION TRIAL
              classes:

            - tile_template: simple_percentage
              tile_id: precentage_chart_swat
              title: SWAT REGRESSION TRIAL